# Convert SSH Public Key to Age Public Key from SSH Public Keyfile per Host
# nix-shell -p ssh-to-age --run "ssh-to-age < /etc/ssh/ssh_host_ed25519_key.pub"

# Reencrypt the secrets.yaml file with newly added key in the secrets folder
# sops updatekeys secrets.yaml

keys:
  - &sops_jf age1shm2ngtau6rk3a08xqvxfml6nqp94kj6qjgzc3h4fd36h29y0apqg88dd4
  #- &sops_convertible
  #- &sops_desktop
  #- &sops_framework
  - &sops_server1 age1s538qv8485s4uhcatznj5e9agcrglmxneajxxvqwtfet006psaeszwcp0w
  #- &sops_server2
  #- &sops_server3
  #- &sops_jf_laptop age1x040lec9y6mtkcncsgfpwc7svyrw9rke4gltlcv06pcvcweczaps30fxed
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *sops_jf
      #- *sops_convertible
      #- *sops_desktop
      #- *sops_framework
      - *sops_server1
      #- *sops_server2
      #- *sops_server3
      #- *sops_jf_laptop