keys:
  - &sops_jf age1shm2ngtau6rk3a08xqvxfml6nqp94kj6qjgzc3h4fd36h29y0apqg88dd4
  #- &sops_jf_laptop age1x040lec9y6mtkcncsgfpwc7svyrw9rke4gltlcv06pcvcweczaps30fxed
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *sops_jf
      #- *sops_jf_laptop