#ENC[AES256_GCM,data:LRxbVos1jl2Sp65j7TvV6qvIEEsZ/fYDC9buYJA4xBj+73LvVqg=,iv:KT/0NFIiQKsD7yPtZYwx0tR4Nds5vXtVQDvE6bb4a6k=,tag:ho62znq5pOsMB3Xi6nibqw==,type:comment]
#ENC[AES256_GCM,data:qzswQDpzNGUXQQ0+ZVMrXYdv+wjDVcFURjP/efdLXyBbH8fpbVzFiAO1T71rBUKDXGcY0rolgds=,iv:iO4qLRv4pjXkYTHO6UZgIEWwup8KSaACQ/PE1851eCo=,tag:Xr4X4mS8sZ1dYDyf7Muw1g==,type:comment]
#ENC[AES256_GCM,data:OotStxLyzPimLDISzAy9F90cqmtH+ESRsbxs15AAWnBUQfZ8kJXwYcCL4nLpj9whVZlwSDryQhnMKR56WKNC1Zt8UFpXxGeV,iv:SRoyR907L3fml9yC6LNGijFvdRf5BHQGm7Qh67+M0Zw=,tag:KhmeOeXkq80GncCKPDYtxQ==,type:comment]
changeme: ENC[AES256_GCM,data:jhtkuP5nZ7s=,iv:DpZDWyweeoW0v2IVpveTFdp1iaTKOb4/TuSdjgyMenU=,tag:CkfIDM1WKTmWkkUYTrRvsA==,type:str]
changeme_env: ENC[AES256_GCM,data:D5pqJ5aZ24g=,iv:KQ2fVoa6PyhBqEBiDdj5QuyS5fKPSTVMcWYZ2dtQ/nY=,tag:bLmIVWg9ZEf/shLelzOZ9w==,type:str]
wifi: ENC[AES256_GCM,data:h3qQ9+zYROdeJ8ab8/xT6i26d/+0T0jC+0v7u0WXH40bBv6ewb11q1R4OkTL/nnVR2Ht3hDhHY8CfQtkfQ9F36PI+Dj7jmfFEbkdntT8jCXbjg2LOn6sqUceUp/+gT5wAmAhCAtN2BXJ3a5LYqFjSTOpJ7Zq0Q4kbrszzuHyEfEfeILOoi8IlxXZCTXnJzkHdpMuPudLGQe2YYSfEy49titEr7gjqfrcovS0wEdgHA==,iv:5JyIeJP+rp2lGEBKrQFlagWQcGq+qn91tSnG1dmWDlY=,tag:wBSgmZxHLHUchNX2SrNNMQ==,type:str]
wireguard:
    home:
        privateKey: ENC[AES256_GCM,data:nH5IkOShgYsc2PNVSrv4P5Bkq+T49LLqHvBMXjIJ8ztZVRS30c3KmrtqeBw=,iv:VIZHj0KOrG10iEc+Nj3XRoNR4qOML5JdgbVCxpGTLW0=,tag:BLjRmYwGS1AyhIfVGrc17g==,type:str]
        presharedKey: ENC[AES256_GCM,data:UmZhUuSuf/ys0BbF7g4DrbJ9sV8tAoiuKjlmGD1s35VFKrI1Kgray2PqSEw=,iv:M7U2MNOJwY1lB6cIVEGeY4LRfJilNT5O8okXCiLlY7Q=,tag:njKyE1A9oMhSALA3XwXkvQ==,type:str]
etesync:
    secret: ENC[AES256_GCM,data:H957d2+sozz5HhV2HHRhMvaei5S2Pk37vBgVCUgKU8U3r9UTTIf57urO0B9rz/q6Qm3OjySC5kfnZEtXN69l7VijRD/iXkrbcCQJntIrx+E9SwxBR/S0K34idK9D8HRvHEEjaHIJ5PokDJxybIVgvO5KQG7nvAuNpjh2wCMm6p0=,iv:8O3+YVjhkTF4PCAZJAzzDBI4Ifc6B0X9RMGMOQfzTDY=,tag:2Q9xU9sO9QWvrTwBpK91gA==,type:str]
    users:
        admin:
            username: ENC[AES256_GCM,data:tQT7ATo=,iv:sDrO0Zp2J8LT+HtBiHWrH+yaT/D08dqQ9qrJQWgZCNo=,tag:AnerrpqktojPYJbYzwuxuQ==,type:str]
            password: ENC[AES256_GCM,data:ZVWf5vyhpYjilQdbW+tDqA63LYmtQKV5XAC/Vh/aZQDNm7nV4t5T35iAoViJQsSq9DgnAXh6SjGDAydsocd5H4Ni/pBk5EeNYjXKtKc6zP6YSAuTtR6GpqZvbXkxGR8qnwvy7YGdFo1fH5QrJ+7+kdcGHBzbh/RnczWr9BBqf6Q=,iv:RQsAPKhrTDQcNvuxMiIH/Vsb385ogZxZ1H1o62rkw+M=,tag:VXEq0GZCx1VhJ3EwW5IDhQ==,type:str]
firefoxsync:
    secret: ENC[AES256_GCM,data:5+gpxAJ5W28yRLLNLz4Mh5oFn9zwnpXrhuKgFIhizaeKPh8JeEETBBsdW+rPkiwQFWSsT5nT2GSjWuRW6i2F1nRZEjkV4LDjqeu0wV8LXJrhJsTERWODcW+9mUPzwWg0RgCpukb2Uy4RaBf20MjKuK1U39Id4Ki44tyap+JcQ5tCD2DdTVXtY56GQqNr5XInS+LI,iv:v1MOmUmGm9d4FOGRNupdb0E+FTI5+p0LRV6KhoAG8lc=,tag:LFDh4yThWp/lKyvpZj0fmA==,type:str]
homeassistant:
    longitude: ENC[AES256_GCM,data:sMpu,iv:Y7v/jmR8r8D3weY+qiIiFFi9PUISGwuHp014dPRMI+c=,tag:1M1RhTdL8ydMsj6VfnhdPg==,type:str]
    latitude: ENC[AES256_GCM,data:DhFdiw==,iv:x0BJ8CLizB0GsaAoanUCyd9kkl6uZmY1Q/iMEfeUMDw=,tag:tPdUvVrLSfDEcikDpaKFvQ==,type:str]
mailserver:
    users:
        admin:
            email: ENC[AES256_GCM,data:T74BLbaP4sAVmrEMUTDqfiI=,iv:FqtNYH4lCcqxqpXq63XEYAEemj8Wp8FO78nkwqMqdEI=,tag:3d3rIs81IHjSVfAgOgP9TQ==,type:str]
            password: ENC[AES256_GCM,data:uFS8Ovp6ve2HWTfYP0Q9YxnbkkMRCULEC6sV3nNg6PsU6le2m8FfUww1JekXPIs17Em3GR3QJNmEKYBD+Zr3BARfCsm+flrSChJ1VwB6rDdcr7SvcYC8gcQZpFD/NPfFqlVxH1UsmwXcIF8RwG7Xe4+Biuz6tXK3E6nkCcz+ie8=,iv:ZKLMZ/NOqfsONYSpQl9owAsRF/Axwz+A3u9rvcoB03A=,tag:qhKK1KBYIecTCODloXsbIw==,type:str]
        jf:
            email: ENC[AES256_GCM,data:cXLxYGS78YA3kIDZhXc=,iv:qtaDqdfqBEr8IT0XRtFsykmaTK6LXc5A/5sCe/Lp5FQ=,tag:w7rP6fvD0zxhIlnP/+lXdg==,type:str]
            password: ENC[AES256_GCM,data:MsBCjzGZbTweqrgzOaCdOmm4Yc3JRCvkzgEfxuDy536PU424L8u/H05vxTLKbRuW5gSF5cMwru74oe0wmCNXeHfIvzYbGaMqJMLuMnWHxMe+7yK49jzGXx7M1n5UiG3QqXDcotiaOy/4L8pCLGvvI8lXhKfej0t7eUFlUP+d16o=,iv:kjeR0LzaQMRB5Ig3daCdmYMFvUwmNR6XExBlsbwWkyg=,tag:Di6occG8C3x9/LXGhjjSig==,type:str]
        sirmorton:
            email: ENC[AES256_GCM,data:+lmKMG6y1jBi7a8iSHuQdFHsizjO,iv:Ct4PNjxqdZrYqOykPK4zgFAocB0wNTelZR80HvMtJhQ=,tag:veYA/BETcOagvq/59cK0Iw==,type:str]
            password: ENC[AES256_GCM,data:Xx7lq6AXMyDZcoLypnahHrf5zkjgZlH1sh1/N3rbmZJ9J5xraOY30NYHbFSQLfW/XtyuIH5qMtC9FoNuML2tlCo9muZtFVM2M3jOPqZyt1a7mlPn+55UAm6yq4vq3i2/dUyTxw4Y/f5Rem7oqyjYALxwj8aPVhSnGmg/mFaN78g=,iv:DGcxZFn/YBXPvfKV2V/CEwB3BwOSdX0hSzd3pvY3I+s=,tag:TTds3s83F/YEqn1nvPHgQw==,type:str]
        xerhaxs:
            email: ENC[AES256_GCM,data:36TrHKvuU9647UjSs2SWs9b0Mg==,iv:ELVnlCau9Kb9NfCPtE8AjKNX6R41OZS1FTsvEQJjRuU=,tag:1MLfpN1iDgSljysnYOMp8A==,type:str]
            password: ENC[AES256_GCM,data:6RzSXYMc6KRRpiNZcboA8KPVsuB50LrR/rrf1hhHxUY4Ln/zricpvzUoid2Ij1eCZW1Evf7DIzMgkJ6QmYuG1GtLDtg07CsQoK4u4hbAIsaJp0aaaDMGi1LGNIgAaRkBjCgz3RA1E1hMVoz+lnEfLNnKGCdO8R3Ljr7+NaPXoss=,iv:1M+cki7KV2VBJZBfEv1xyJktLUy409hIS6GhO69K/0w=,tag:UEoM5Xv0QryLxrmSTzNILw==,type:str]
monero:
    users:
        username: ENC[AES256_GCM,data:0aHDNFw=,iv:mdXbfjejOnESFFMa6eJ4rFQYLWkT5KBEuEIlrQ7WrgQ=,tag:t3SapmivCqh2DCRBMEndWQ==,type:str]
        password: ENC[AES256_GCM,data:2SPb1VtUagk9e8K51w7PFIaztGz8Ep3B8dvad0l/roJx6eaNV2ZqgMVixTFcee0hEzhn9Ingp5Vz+oWWatQSoFw0tphV5J5IUenum3RjjDUCQc5U+Vaenrxc7BtlibqbpI2JPddC8sQlo6J6Btu5lpNojdtA+uha65gxqDprGcc=,iv:SMKxQozO/DpjocVgUGZksPTHmrZRL/Qye0A/UoVcwmY=,tag:tn86GbSvcU7reLzEcMU7qg==,type:str]
        address: ENC[AES256_GCM,data:kIbq+lAp0kJsFQ1o/vx9jT1tq1Zk0wxbpF/va//kgCw6JZTQ6753uAA4J0b66SN9oHVm4n0QJyGFogcTkfB/d1n7d3761QdflsBXu5p/tDuKF/VaePdnbJAAJhYLPvQ=,iv:yfZfOHUyHOh7UIa6xJG93AnjxALMKb8ZRVrPphNnOuc=,tag:phG8GY+VIxNRX0pRIUbAxg==,type:str]
freshrss:
    users:
        defaultUser:
            username: ENC[AES256_GCM,data:OqncJmYotvXOXwOX+pJgcPwq,iv:hQtRipclMoFe4vLn3I4hJg1fyS7YdevHP+oS64I/3dQ=,tag:87CLFwvpyPB/ldcFqvoSKA==,type:str]
            password: ENC[AES256_GCM,data:vyxYcQigAyVRhNCKuAcrqoXl9lTGIEgDOs9lcl9v2AmHxbrLKhUgGprwpM+DWFre2p1P1Q/QV4os8GhjeGwcqM3dQsv98LArWP6sCY5gmmf74ag+YEVFH+mOnIAXCnRLG5yEsg2nLCNJVLW7Tmt6+YOkczB+gyFFDdXYYxWC/Bs=,iv:n2UCy/06gYDq7L4qmukBnm5HSgwYT8M0ufeLSnjw7vs=,tag:9Ob4uZwoRZlx2JpUYdGDvQ==,type:str]
nextcloud:
    users:
        admin:
            username: ENC[AES256_GCM,data:STyRjAM=,iv:g/MPH0/XdtEpDTw245SVPHAG6e/+MLgKg6Y7tOPuRFM=,tag:pbxs/hyDby7cQqovtqK5iA==,type:str]
            password: ENC[AES256_GCM,data:4gCptpm2VsENxor2PMCjVVqtJgcAP7lIjVqwgwmd0ZlXqH55xO2xPtp/v9c9ksB0nW04lrar4+RkuggMhJRXQ04wiMaPePhAcFuWSOtzzW1GoBvFT52kZgLYXrEeZ8kVksXhdgzkYyrYYKWw5+MDxPMGLl4ifU3qhUakk8warK4=,iv:SdKFwygTGq+gQl13NDT5N2liVWW/7pTLiBICNx93QZY=,tag:S4UdtUNsWcqUp1bbOaQG7Q==,type:str]
nginx:
    acme:
        email: ENC[AES256_GCM,data:G4GiTiEtfeLVKVa2P0fFa2OkpSuyFHscOY0Z,iv:OiYKMKzoW81y4bP7lJKBVhfKXTYyB5zMPk0l8FIRP+s=,tag:T9KRAyT4CqpYNevDY18NAQ==,type:str]
        api_key: ENC[AES256_GCM,data:peI/a06lsI1BUp606P5S5HWHsTgRXN1c5ZDjdEVTznUq0d0X/Px7jrGRF/NoQVKRr3XHdtlJRSqQbofYDQ3tzyZ1bvy6FJRIzuvOocfjIvo7pPR2+0zDrNZm06703fkKeMM0+pJYzgxLauOBqUEwSt8cPs5+UB9okri0UHCiWdh9EM6SnA==,iv:k+vR0w+6JDRtWdPdnvq6spOQvZHqZp9KVJ/Gl9YoGaI=,tag:KuP87M0lI62pLmb5RsHIfA==,type:str]
nzbget:
    control:
        username: ENC[AES256_GCM,data:zOiF3Fg=,iv:PQ2E2C3d07I4M77jx87/M9lZQ+aWQtx2GqVJOlsByBg=,tag:xdQIvegrxua0VWwtCrPnyg==,type:str]
        password: ENC[AES256_GCM,data:HzAqZasiUWEh0v5Pmob6KSYLwKnkrr1/Pt5PGklNuWPwJ0dCUzpXRY9HekekeZuktyx/l4mVr/nuyw7SydnKMTZkoqMCDlwPHj/J95UDjSkyi2zWN8p0hsFkL5tNbWJnLhPgpBcKBY5Fi5bfkuaIdmuqJZUx3J9kNDblZcqXhV8=,iv:69nIukifgqt3r1R5x+Sblrf5jZkYHb7xPU417Rr5xFc=,tag:SVy0bdWZDnrTIzK0DdYsXA==,type:str]
peertube:
    secret: ENC[AES256_GCM,data:RE2Dbos7OcfW7GR51jAi9VOPabTWO89w4K8qULM/pDzvn7BGhBE2gKftQwn3JoZhkyoNG8FI0J18BZiyMm5yGQ==,iv:nr0p0WKU4FN/biuVh01vL0MzNhpzP0frKMSwTTYSP8U=,tag:dO00mT6ZSpI/56bwn1swlw==,type:str]
    smtppassword: ENC[AES256_GCM,data:FLs8YGXEqfJ9sp+ElioWKF2m5oYVV+y5xJaH6hSqr9rmatIJT59RM+zu0BNfCRW4nfnfuVGA4Yl9layN8ikJqpWmV9CJixy55jtg2PcC8Ts1KTC9LmK9UNKLlj5qoi88HyxYxB1yt3wXiiK3R+kugcfh8J/qBYkkixIOh4HinxM=,iv:mLlFtWtfPF8O0VWqCUJtICruLQL6CpyOcREj8jMJFsk=,tag:nyUUfJSpMZqVpDEaALFd5w==,type:str]
    password: ENC[AES256_GCM,data:gyLd7q236RuYDkyxh5KintLNqioeHqRmFy6sjNshe3jg52U7B2MvhKsKuQgklsvpXYFmcsFDcuzl7FqYSFMxKtI9Puf73oH6w4pJSWD5l4KQ9bdyxLOPhJPCWSfnkcys/+nlLdPaSKr0CO8YCvf6l4F/+/6IzjrxiB0cA146bnY=,iv:4dRmUOr/zuxdehRjWTMxMv6HzL+7O0RZ1XAV/DyM6r8=,tag:+lMWx9SGNG+8ITBucZVCeg==,type:str]
pufferpanel:
    users:
        admin:
            email: ENC[AES256_GCM,data:oa7Syz1MjNCdYoBRVtGBaYwqUTMZn2iNW9ym,iv:a2UuSEjVjxRwk1xm0ZmqQKnzYNXUH3qOFu4U6e59NAU=,tag:rt/wCqpS4rmQVr6nM6Kbag==,type:str]
            password: ENC[AES256_GCM,data:BiLkQnAFOegXTPWYO9LK1JiuLCCQOP5FMPGk3bncp/Y+QkfmHogdRGjC8x1YPcLxcEFedbcSJIShBtxD9qYm7yCShcjyY8PQKl5n2fV9a3F40BeJr0arkgQn61bjRTge1VaCoOvJGPzUZEYBsPJXjs8ZWNwscRfKJQLHyrG1e3J/JrXSyOgF2+6jZcn1,iv:Y/AYKlclhS6wUrCh0Ptcpq37KWp7xzONVjpWKjAqY+w=,tag:gbeRkPg2q1nN6T9gjX8Vzw==,type:str]
radicale:
    htpasswd: ENC[AES256_GCM,data:H6eia3RE+T0NOPe4jds8fnSSJVbQrZmVTUhDdLiy8wOey2hSoErTVruti7mHjzZWww6KtcafowuL5PCDn4zGVb+KsVMuIT/nVm+m+WZZ/53Wbp6N1x0WZ08iPhusNgGqHH3/Vfhqkp5IlSbd1O1PlGdVQeP/qqSi3HE15iFYtCfOnovFz7Q=,iv:09I7gdphTlLevLmx18k5Hdag6ObkNZwRoGr4tp6Bte8=,tag:kJs0JaRbCIRhlB6CTAWYOA==,type:str]
    #ENC[AES256_GCM,data:rOHSLaMOwaaOpuGJUPq0Sj0wzQhHKsbMCqnaL6SnhaYQMqDS7atBIladWMWbSAVull1kH2ugD6OW6lM319WLIrjLmYH+ynJNviCg8w==,iv:jhV9CjaDSlTMwBpXHjJBklTsP4xx/lWRCcuq/eKbtUM=,tag:LAlFHNTLrRtS4yBr3fBZKg==,type:comment]
searxng:
    secret: ENC[AES256_GCM,data:1utQPL/XLrwpYn6mLdcltrclwfzO/kQOiZQSOl6B1FhUJOjd6Wj1sVRxR5HXt8eDpZ/Ucq0CHrFEGXaw+JK3FHIujRQgWZg8VeHy0Vni7Q4t3yWMlxVm097DAiNs4oqA2jHjGPGmdOhbb7nOaQpxDt9MhmhH+CUrthGDkdLk110r6iKL5rYsTFmFnYDb0KECqQ==,iv:2+dYILIaPwe1vjdlpFdApz4YEA4fvNLpnos/z1qbDb0=,tag:3HlWjW0yAVRfD9qhrwwcFQ==,type:str]
webdav:
    users:
        admin:
            username: ENC[AES256_GCM,data:1j+mwpumA9igkVJL+57cGmpJ,iv:Qq9zwGuX2t/xu9NIwfsD/vYhwrGevbqrklsP9T3onN0=,tag:EYkrz4vjV6CzmNrRfcJFCg==,type:str]
            password: ENC[AES256_GCM,data:BQ1lJQtJGX3DJ5r2a38TPynZxVpzWseJKSm9FWXYsSNVhQbh1Rf2oO2VZFggXrruHAKOjRgnKWTdlutEHWxi67W2l3uqhqq0HjwjDbkBwm8W6vG7zxy5cve2QZZpHdvYiXJa8VvIrU4iFqoTi/VLN4b4xLcMIcNHPMug89F7S+kMTZxFe1bMkmlqq1cB,iv:tsbk21S/g2dkUPpI13sC4OKsXPi6myBaUCTd74+hlvU=,tag:O4xn+vpH+AfWOm/o59ioEw==,type:str]
synology-nas:
    user: ENC[AES256_GCM,data:S0exBt2B0UnSc4QOUftpGJm485eQk5COGYY3nJx1h8B+KA==,iv:cFumMmVzICOqtq+hmWmbhnMJaTJw9irK/WB53a8GtDU=,tag:whyJt3zmvBh1n0/BNTZRqg==,type:str]
syncthing:
    nixosdesktop: ENC[AES256_GCM,data:A4mzkLNt5uSPLTmYUiAYM7vcGkKiyQHjbhGwKqapXEo/wo4R02vXJmSX6FXutOHWHi1vZrTNpkpBol0JzMCA,iv:SXGnlyCp7OzYHIdh5M9zN8EyD9y2rs5XeJGKKUG+YGY=,tag:R1z2He12o6lmB+7NE3kYHg==,type:str]
    nixoslaptop: ENC[AES256_GCM,data:L3nwI3vX/qvwhe2NRja9gDez2dEVE6gbjC2NPOfAUGXOUWd8opbf9qGidNqJEJKzvs7iUVI2vOBVrsvlwKyM,iv:rhGpyw7hGcVRidqcT69g6tIIv+zFeXJmXUDm29ct0Ng=,tag:/K98gQCAqc92KDoUaSsWfg==,type:str]
    graphenos: ENC[AES256_GCM,data:wFaqyhjBnVykP0FUhNB7TazZn3mq8xO7bfVYv/ZW60pLpNkeJJgLWpalW9XMGt2lmHZ9i3WMyfAzIaZYSg9R,iv:yZrGKVAY+tTHYS2+v6/aLxBaP4BrH2XnQwVKulEZq1I=,tag:8JKvWGeHf0762pUwOyRxVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1shm2ngtau6rk3a08xqvxfml6nqp94kj6qjgzc3h4fd36h29y0apqg88dd4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpL0svQ2l4dWxuSGVHWWFu
            VUxFR0ZTNWJob09ib2tVckpaUTZpWnR4OXljCjV4ckprV3cvcXhxc0IxSUtRQkMz
            clY0TzJpM0hoeGY5MkJZRHJSSFhEbTQKLS0tIHh5Z0VTMFZaRXhLcEdIRWJ3RzNF
            cFN1bnlnOFJielRldXlNU3JrTjBRZFEKwTGkznlrV+pIGpNrgO5DLEnxUThnk9CE
            mTi77ladj3kDfJdw6Dh/YdZSSRL0tBe/ke7SAas5L1BWjCA2l0NjAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-12T08:06:46Z"
    mac: ENC[AES256_GCM,data:8CnuW+vrOW68wSgkBaS2qRL64ewPTtDc4Vq3Y44L8J9tSoEA/Ggj0SMk2HWQaliQfV7sxD8wSKYiTRq+lNKw5vql7DyfZUoGAOqj6wjW9NMYziJjhtaGRwyQjOj/Q0nAZOpJUnAP1DjN1Fy6lsqfTk5YcRkKQw+5D7LeF+yue9o=,iv:iZ8+vgLcw3j8nC8fkS3df0RQq2Rqoi4fwNF7A5Dm5Nk=,tag:K6FSLRFrwAi+dRHLzNDFwA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
